// Central tuning constants — adjust here to rebalance without touching logic.
export const BAL = {
  ap: { bacteria: 3, virus: 3, immune: 3 },

  bacteria: {
    reproduceBiomassCost: 4,
    reproduceGain: 3,
    spreadBiomassCost: 3,
    spreadFailBiomassCost: 1,
    spreadGain: 2,
    spreadThreshold: 5,
    biofilmBiomassCost: 3,
    toxinDamage: 6,
    toxinDetection: 8,
    toxinApCost: 2,
    resistanceGain: 8,
    resistanceBiomassCost: 8,
    resistanceApCost: 2,
    hideBiomassCost: 2,
    hideDetectionReduction: 10,
    passiveBiomassPerColony: 0.35,
    hexCap: 12,
    victoryHexesControlled: 20,
    victoryMajorOrgans: 3,
  },

  virus: {
    infectVirionCost: 3,
    infectFailVirionCost: 1,
    infectGain: 2,
    infectThreshold: 6,
    replicateGain: 3,
    replicateSelfDamage: 1,
    burstApCost: 2,
    burstFractionConsumed: 0.5,
    burstVirionGain: 8,
    burstSelfDamage: 4,
    burstDetectionSpike: 6,
    latencyApCost: 2,
    evadeVirionCost: 3,
    evadeDetectionReduction: 10,
    hexCap: 12,
    victoryHexesControlled: 18,
    victoryRegions: 4,
  },

  immune: {
    neutrophilCost: 3,
    neutrophilApCost: 1,
    macrophageCost: 4,
    macrophageApCost: 1,
    macrophageDetectionGain: 6,
    inflammationCost: 3,
    inflammationApCost: 1,
    inflammationGain: 15,
    inflammationDamage: 3,
    feverCost: 2,
    feverApCost: 1,
    feverStep: 0.5,
    feverMax: 41,
    feverMin: 37,
    tCellCost: 5,
    tCellApCost: 2,
    antibodyCost: 5,
    antibodyApCost: 2,
    quarantineCost: 3,
    quarantineApCost: 1,
    quarantineDecay: 0.25,
    adaptiveThreshold: 40,
    adaptiveThresholdLowered: 30,
    detectionPassiveGain: 1.5,
    memoryGainOnClear: 15,
    ipBasePerRound: 4,
  },

  cytokineStormThreshold: 65,
  cytokineStormBodyDamage: 12,

  hexRegenPerRound: 2,
  microbiomeRegenPerRound: 1,
};
