import type { RegionDef, RegionId } from './types';

export const REGION_ORDER: RegionId[] = [
  'skin',
  'nose',
  'throat',
  'lungs',
  'bloodstream',
  'heart',
  'liver',
  'stomach',
  'intestines',
  'kidneys',
  'lymphNodes',
  'spleen',
  'brain',
];

// Positions are percentages on a stylized front-facing body silhouette (0-100).
export const REGIONS: Record<RegionId, RegionDef> = {
  skin: {
    id: 'skin',
    name: 'Skin',
    icon: '🩹',
    x: 82,
    y: 38,
    connections: ['bloodstream', 'lymphNodes'],
    description: 'The body\'s outer barrier. Wounds here are the most common entry point for bacteria.',
    traits: { bacteriaGrowthBonus: 1, vitality: 4 },
  },
  nose: {
    id: 'nose',
    name: 'Nose / Upper Airway',
    icon: '👃',
    x: 50,
    y: 10,
    connections: ['throat'],
    description: 'First contact for airborne pathogens. A common launch point for viral infections.',
    traits: { virusReplicationBonus: 1, vitality: 3 },
  },
  throat: {
    id: 'throat',
    name: 'Throat',
    icon: '🗣️',
    x: 50,
    y: 20,
    connections: ['nose', 'lungs', 'stomach'],
    description: 'A crossroads region connecting the airway and the digestive tract.',
    traits: { vitality: 4 },
  },
  lungs: {
    id: 'lungs',
    name: 'Lungs',
    icon: '🫁',
    x: 50,
    y: 34,
    connections: ['throat', 'bloodstream', 'heart'],
    description: 'High oxygen, huge surface area. Great for viral replication, but damage here hits the whole body hard.',
    traits: { virusReplicationBonus: 2, highConsequence: 1.6, vitality: 10 },
  },
  bloodstream: {
    id: 'bloodstream',
    name: 'Bloodstream',
    icon: '🩸',
    x: 50,
    y: 50,
    connections: ['skin', 'lungs', 'heart', 'liver', 'kidneys', 'spleen', 'lymphNodes', 'brain', 'intestines'],
    description: 'The great highway of the body. Fast travel for pathogens, but also heavily patrolled by immune cells.',
    traits: { immuneBonus: 1, vitality: 9 },
  },
  heart: {
    id: 'heart',
    name: 'Heart',
    icon: '❤️',
    x: 42,
    y: 42,
    connections: ['lungs', 'bloodstream'],
    description: 'Keeps blood moving. Rarely infected directly, but catastrophic if it fails.',
    traits: { highConsequence: 2, vitality: 9 },
  },
  liver: {
    id: 'liver',
    name: 'Liver',
    icon: '🫘',
    x: 60,
    y: 56,
    connections: ['bloodstream', 'intestines'],
    description: 'Filters toxins from the blood. Damage here lets toxins build up throughout the body.',
    traits: { highConsequence: 1.5, vitality: 8 },
  },
  stomach: {
    id: 'stomach',
    name: 'Stomach',
    icon: '🫄',
    x: 44,
    y: 58,
    connections: ['throat', 'intestines'],
    description: 'Harsh acidic environment. Hostile to most pathogens that pass through.',
    traits: { vitality: 5 },
  },
  intestines: {
    id: 'intestines',
    name: 'Intestines',
    icon: '🌀',
    x: 50,
    y: 68,
    connections: ['stomach', 'liver', 'lymphNodes', 'bloodstream'],
    description: 'Home to a large beneficial microbiome that competes with invaders for resources.',
    traits: { bacteriaGrowthBonus: 2, microbiome: 60, vitality: 7 },
  },
  kidneys: {
    id: 'kidneys',
    name: 'Kidneys',
    icon: '🫗',
    x: 58,
    y: 66,
    connections: ['bloodstream'],
    description: 'Filter the blood and balance fluids. Sensitive to toxins and dehydration.',
    traits: { highConsequence: 1.3, vitality: 6 },
  },
  lymphNodes: {
    id: 'lymphNodes',
    name: 'Lymph Nodes',
    icon: '🔵',
    x: 35,
    y: 48,
    connections: ['skin', 'bloodstream', 'intestines', 'spleen', 'throat'],
    description: 'Command centers of the immune system. Adaptive immunity develops fastest here.',
    traits: { immuneBonus: 3, vitality: 5 },
  },
  spleen: {
    id: 'spleen',
    name: 'Spleen',
    icon: '🟣',
    x: 65,
    y: 48,
    connections: ['bloodstream', 'lymphNodes'],
    description: 'Filters blood and helps immune cells mature. A quiet but important immune asset.',
    traits: { immuneBonus: 2, vitality: 5 },
  },
  brain: {
    id: 'brain',
    name: 'Brain',
    icon: '🧠',
    x: 50,
    y: 4,
    connections: ['bloodstream'],
    description: 'Protected by the blood-brain barrier, making it very hard to enter — but devastating if breached.',
    traits: { bloodBrainBarrier: true, highConsequence: 2.5, vitality: 10 },
  },
};

export function getNeighbors(id: RegionId): RegionId[] {
  return REGIONS[id].connections;
}

export const MAJOR_ORGANS: RegionId[] = ['lungs', 'liver', 'heart', 'kidneys', 'brain', 'intestines', 'spleen'];
